export type CoreValue = { title: string; description: string };
export type AboutPageContent = { heroTitle: string; heroSubtitle: string; storyTitle: string; storyBody: string[]; images: { src: string; alt: string }[]; coreValues: CoreValue[] };
export type ContactInfo = { address: string; googleMapsAddress: string; mondaySaturdayHours: string; sundayHours: string; supportContact: string; whatsapp1: string; whatsapp2: string; whatsappRedirect: string; useWhatsapp1AsRedirect: boolean; useWhatsapp2AsRedirect: boolean; instagram: string; facebook: string; youtube: string };
export const DEFAULT_ABOUT_PAGE: AboutPageContent = { heroTitle: "Redefining Refurbished.", heroSubtitle: "We believe premium technology shouldn't cost the earth. High performance, rigorous testing, and a commitment to sustainability.", storyTitle: "Our Story", storyBody: ["Founded with a simple vision: to make high-end computing accessible to everyone while reducing electronic waste. Lapitex started in a small workshop repairing discarded enterprise laptops.", "Today, we are a leading provider of premium refurbished IT solutions. We don't just sell used computers; we completely re-engineer them. Every device that passes through our doors is subjected to a military-grade 50-point diagnostic test.", "Whether you're a student looking for your first Mac, or an enterprise outfitting a new department, Lapitex delivers uncompromised quality at a fraction of the retail price."], images: [{ src: "/our-story.png", alt: "Lapitex team in the store" }, { src: "/store-interior.png", alt: "Lapitex store interior" }, { src: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=1000", alt: "IT workspace" }, { src: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=1000", alt: "Laptop workspace" }, { src: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=1000", alt: "Refurbished laptop" }], coreValues: [{ title: "Uncompromised Quality", description: "Every component is tested, cleaned, and verified to ensure it meets our strict performance standards." }, { title: "Sustainability First", description: "By extending the life of electronics, we actively reduce e-waste and lower the carbon footprint of computing." }, { title: "Customer Focus", description: "Transparent grading, honest pricing, and dedicated post-sale support for absolute peace of mind." }, { title: "Industry Expertise", description: "Our technicians are certified professionals with years of experience in enterprise hardware." }] };
export const DEFAULT_CONTACT_INFO: ContactInfo = { address: "Union bank in building, Chandi vayapar bhawan,\nW2 2nd floor, Brajkishore Path,\nnear Pillar no 15,\nPatna, Bihar 800001", googleMapsAddress: "LAPITEX IT SOLUTION, Patna, Bihar 800001", mondaySaturdayHours: "10:30 AM - 8:00 PM", sundayHours: "12:00 PM - 5:00 PM", supportContact: "+91 6200144824", whatsapp1: "+91 8809975386", whatsapp2: "+91 8789710408", whatsappRedirect: "+91 8809975386", useWhatsapp1AsRedirect: true, useWhatsapp2AsRedirect: false, instagram: "https://www.instagram.com/lapitex_it_solutions/", facebook: "https://www.facebook.com/lapi.tex.2025/", youtube: "https://www.youtube.com/channel/UCP-jwgZHGVovyKdYZm4yFIQ" };
export function mergeAbout(value: unknown): AboutPageContent { const input = (value && typeof value === "object" ? value : {}) as Partial<AboutPageContent>; return { ...DEFAULT_ABOUT_PAGE, ...input, storyBody: input.storyBody?.length ? input.storyBody : DEFAULT_ABOUT_PAGE.storyBody, images: input.images?.length ? input.images : DEFAULT_ABOUT_PAGE.images, coreValues: input.coreValues?.length ? input.coreValues : DEFAULT_ABOUT_PAGE.coreValues }; }
export function mergeContact(value: unknown): ContactInfo { return { ...DEFAULT_CONTACT_INFO, ...((value && typeof value === "object" ? value : {}) as Partial<ContactInfo>) }; }
export function digits(value: string) { return value.replace(/\D/g, ""); }
export function whatsappUrl(value: string) { return `https://wa.me/${digits(value) || digits(DEFAULT_CONTACT_INFO.whatsapp1)}`; }
export function safeUrl(value: string, fallback: string) { try { const url = new URL(value); return url.protocol === "http:" || url.protocol === "https:" ? url.toString() : fallback; } catch { return fallback; } }
