"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ArrowLeft, Save, Star, Upload, Plus, Trash2 } from "lucide-react";
import { parseSpecs } from "@/lib/parseSpecs";

type Row = { key: string; value: string };
type CustomerReview = { id: string; rating: number; title: string | null; content: string; isTopReview: boolean; createdAt: Date; user: { name: string; email: string } | null };
type Product = { id: string; name: string; description: string; price: number; originalPrice: number | null; stock: number; category: string; condition: string; imageUrl: string | null; imageUrls: string | null; discountBadge: string | null; specifications: string | null; technicalSpecifications: string | null; nonTechnicalSpecifications: string | null; showTechnicalSpecifications: boolean; showNonTechnicalSpecifications: boolean; warrantyMonths: number | null; warrantyDetails: string | null; coveredItems: string | null; supportDetails: string | null; overviewQualityTitle: string | null; overviewQualityText: string | null; overviewReplacementTitle: string | null; overviewReplacementText: string | null; reviews: string | null; deliveryFee: number | null; deliveryDays: string | null; customerReviews: CustomerReview[] };
const inputClass = "w-full px-4 py-3 rounded-2xl bg-pink-50/40 border border-pink-100/50 text-sm text-[#2d1a26] focus:outline-none focus:border-[#e1467c]";
const labelClass = "block mb-1.5 text-[10px] font-black uppercase tracking-widest text-[#e1467c]";
function json<T>(value: string | null, fallback: T): T { try { const parsed = value ? JSON.parse(value) : null; return parsed ?? fallback; } catch { return fallback; } }
function rows(value: string | null, legacy: string | null): Row[] { const parsed = json<Row[]>(value, []); if (parsed.length) return parsed; return (legacy || "").split("\n").filter(Boolean).map(line => { const [key, ...rest] = line.split(":"); return { key: key.trim(), value: rest.join(":").trim() }; }); }
function points(value: string | null) { const parsed = json<string[]>(value, []); return parsed.length ? parsed : (value || "").split("\n").map(item => item.trim()).filter(Boolean); }
const defaultCovered = ["Motherboard and internal components", "Display screen (excluding physical damage or liquid spills)", "RAM and Storage drives", "Keyboard and Trackpad functionality"];
const defaultSupport = "For warranty claims or technical support, please contact us at support@lapitex.com or call us at +91 6200144824.";

export default function ProductAdminDetailClient({ product, siteShippingFee }: { product: Product; siteShippingFee: number }) {
  const router = useRouter(); const imageList = [...json<string[]>(product.imageUrls, product.imageUrl ? [product.imageUrl] : []), "", "", "", "", ""].slice(0, 5);
  const effectiveSpecifications = parseSpecs(product.name, product.description, product.category);
  const [form, setForm] = useState({ name: product.name, description: product.description, price: String(product.price), originalPrice: product.originalPrice == null ? "" : String(product.originalPrice), stock: String(product.stock), category: product.category, condition: product.condition, discountBadge: product.discountBadge || "", imageUrls: imageList, technical: rows(product.technicalSpecifications, product.specifications).length ? rows(product.technicalSpecifications, product.specifications) : effectiveSpecifications, nonTechnical: product.nonTechnicalSpecifications || "", showTechnical: product.showTechnicalSpecifications, showNonTechnical: product.showNonTechnicalSpecifications, qualityTitle: product.overviewQualityTitle || "Quality Checked", qualityText: product.overviewQualityText || "Thoroughly tested by our expert technicians for optimal performance.", replacementTitle: product.overviewReplacementTitle || "7 Days Replacement", replacementText: product.overviewReplacementText || "Easy replacement if any defect is found within 7 days of delivery.", warrantyMonths: product.warrantyMonths == null ? "" : String(product.warrantyMonths), warrantyDetails: product.warrantyDetails || "Our warranty covers any hardware defects that may occur during normal usage.", covered: points(product.coveredItems).length ? points(product.coveredItems) : defaultCovered, supportDetails: product.supportDetails || defaultSupport, deliveryFee: product.deliveryFee == null ? "" : String(product.deliveryFee), deliveryDays: product.deliveryDays || "3-5 business days", reviews: product.reviews || "" });
  const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState<number | null>(null); const [reviewList, setReviewList] = useState(product.customerReviews);
  const set = (key: string, value: string) => setForm(current => ({ ...current, [key]: value }));
  const uploadImage = async (event: React.ChangeEvent<HTMLInputElement>, index: number) => { const file = event.target.files?.[0]; if (!file) return; setUploading(index); const data = new FormData(); data.append("file", file); try { const response = await fetch("/api/upload", { method: "POST", body: data }); const result = await response.json(); if (result.url) setForm(current => ({ ...current, imageUrls: current.imageUrls.map((image, i) => i === index ? result.url : image) })); else alert(result.error || "Upload failed"); } catch { alert("Upload failed"); } finally { setUploading(null); } };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const technical = form.technical.filter(row => row.key.trim() || row.value.trim()); const response = await fetch(`/api/admin/products/${product.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.name, description: form.description, price: form.price, originalPrice: form.originalPrice, stock: form.stock, category: form.category, condition: form.condition, discountBadge: form.discountBadge, imageUrls: form.imageUrls, imageUrl: form.imageUrls.find(Boolean) || null, technicalSpecifications: JSON.stringify(technical), specifications: JSON.stringify(technical), nonTechnicalSpecifications: form.nonTechnical, showTechnicalSpecifications: form.showTechnical, showNonTechnicalSpecifications: form.showNonTechnical, overviewQualityTitle: form.qualityTitle, overviewQualityText: form.qualityText, overviewReplacementTitle: form.replacementTitle, overviewReplacementText: form.replacementText, warrantyMonths: form.warrantyMonths, warrantyDetails: form.warrantyDetails, coveredItems: JSON.stringify(form.covered.map(item => item.trim()).filter(Boolean)), supportDetails: form.supportDetails, reviews: form.reviews, deliveryFee: form.deliveryFee, deliveryDays: form.deliveryDays }) }); if (!response.ok) throw new Error(); router.refresh(); alert("Product saved successfully"); } catch { alert("Could not save product"); } finally { setSaving(false); } };
  const toggleTop = async (review: CustomerReview) => { const response = await fetch(`/api/admin/reviews/${review.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ isTopReview: !review.isTopReview }) }); if (response.ok) setReviewList(current => current.map(item => item.id === review.id ? { ...item, isTopReview: !item.isTopReview } : item)); };
  return <form onSubmit={save} className="space-y-6"><div className="flex items-center justify-between gap-4"><div><Link href="/admin/products" className="inline-flex items-center gap-2 text-sm font-bold text-[#e1467c] mb-3"><ArrowLeft className="w-4 h-4" /> Back to Products</Link><h1 className="text-3xl font-black text-[#2d1a26]">Manage Product</h1><p className="text-sm text-[#4a1a2e]/50 mt-1">Edit every customer-facing section for this item.</p></div><button disabled={saving} className="clay-btn px-5 py-3 text-white font-bold flex items-center gap-2"><Save className="w-4 h-4" />{saving ? "Saving..." : "Save Product"}</button></div>
    <section className="clay-card p-6 space-y-5"><h2 className="text-xl font-black text-[#2d1a26]">Overview</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label className={labelClass}>Product name</label><input className={inputClass} value={form.name} onChange={e => set("name", e.target.value)} required /></div><div><label className={labelClass}>Category</label><input className={inputClass} value={form.category} onChange={e => set("category", e.target.value)} required /></div></div><div><label className={labelClass}>Product overview</label><textarea className={inputClass} rows={5} value={form.description} onChange={e => set("description", e.target.value)} required /></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label className={labelClass}>Quality checked title</label><input className={inputClass} value={form.qualityTitle} onChange={e => set("qualityTitle", e.target.value)} /></div><div><label className={labelClass}>Replacement title</label><input className={inputClass} value={form.replacementTitle} onChange={e => set("replacementTitle", e.target.value)} /></div><div><label className={labelClass}>Quality checked description</label><textarea className={inputClass} rows={3} value={form.qualityText} onChange={e => set("qualityText", e.target.value)} /></div><div><label className={labelClass}>Replacement description</label><textarea className={inputClass} rows={3} value={form.replacementText} onChange={e => set("replacementText", e.target.value)} /></div></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div><label className={labelClass}>Price (₹)</label><input className={inputClass} type="number" value={form.price} onChange={e => set("price", e.target.value)} required /></div><div><label className={labelClass}>Original price (₹)</label><input className={inputClass} type="number" value={form.originalPrice} onChange={e => set("originalPrice", e.target.value)} /></div><div><label className={labelClass}>Custom badge</label><input className={inputClass} value={form.discountBadge} onChange={e => set("discountBadge", e.target.value)} placeholder="Optional" /></div></div></section>
    <section className="clay-card p-6 space-y-5"><h2 className="text-xl font-black text-[#2d1a26]">Product gallery (5 image slots)</h2><p className="text-xs text-[#4a1a2e]/50">The first two images are used in shop and featured cards.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{form.imageUrls.map((image, index) => <div key={index} className="rounded-2xl bg-pink-50/30 border border-pink-100/50 p-3"><label className={labelClass}>Image {index + 1}</label><input className={inputClass} value={image} onChange={e => setForm(current => ({ ...current, imageUrls: current.imageUrls.map((item, i) => i === index ? e.target.value : item) }))} placeholder="Image URL" /><div className="relative mt-2"><input type="file" accept="image/*" onChange={e => uploadImage(e, index)} className="absolute inset-0 opacity-0 cursor-pointer" /><div className="rounded-xl border-2 border-dashed border-pink-200 p-2.5 text-center text-xs font-bold text-[#e1467c]"><Upload className="w-4 h-4 inline mr-1" />{uploading === index ? "Uploading..." : "Upload image"}</div></div>{image && <img src={image} alt={`Product image ${index + 1}`} className="mt-2 h-28 w-full rounded-xl object-cover" />}</div>)}</div></section>
    <section className="clay-card p-6 space-y-5"><h2 className="text-xl font-black text-[#2d1a26]">Specifications</h2><p className="text-xs text-[#4a1a2e]/50">Technical specifications appear as a table; non-technical details remain free-form.</p><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.showTechnical} onChange={e => setForm(current => ({ ...current, showTechnical: e.target.checked }))} /> Show technical specifications</label>{form.showTechnical && <div className="space-y-2"><div className="grid grid-cols-[1fr_1fr_auto] gap-2 text-[10px] font-black uppercase tracking-widest text-[#a48d9a]"><span>Specification</span><span>Value</span><span /></div>{form.technical.map((row, i) => <div className="grid grid-cols-[1fr_1fr_auto] gap-2" key={i}><input className={inputClass} value={row.key} onChange={e => setForm(current => ({ ...current, technical: current.technical.map((item, index) => index === i ? { ...item, key: e.target.value } : item) }))} placeholder="RAM" /><input className={inputClass} value={row.value} onChange={e => setForm(current => ({ ...current, technical: current.technical.map((item, index) => index === i ? { ...item, value: e.target.value } : item) }))} placeholder="16GB" /><button type="button" onClick={() => setForm(current => ({ ...current, technical: current.technical.filter((_, index) => index !== i) }))} className="px-2 text-red-400"><Trash2 className="w-4 h-4" /></button></div>)}<button type="button" onClick={() => setForm(current => ({ ...current, technical: [...current.technical, { key: "", value: "" }] }))} className="text-sm font-bold text-[#e1467c]"><Plus className="w-4 h-4 inline" /> Add row</button></div>}<label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.showNonTechnical} onChange={e => setForm(current => ({ ...current, showNonTechnical: e.target.checked }))} /> Show non-technical specifications</label>{form.showNonTechnical && <textarea className={inputClass} rows={6} value={form.nonTechnical} onChange={e => set("nonTechnical", e.target.value)} placeholder="Condition notes, included accessories, and other details..." />}</section>
    <section className="clay-card p-6 space-y-5"><h2 className="text-xl font-black text-[#2d1a26]">Warranty & Support</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label className={labelClass}>Warranty months</label><input className={inputClass} type="number" min="0" value={form.warrantyMonths} onChange={e => set("warrantyMonths", e.target.value)} placeholder="6" /></div><div><label className={labelClass}>Support channels</label><input className={inputClass} value={form.supportDetails} onChange={e => set("supportDetails", e.target.value)} placeholder="WhatsApp, email, phone" /></div></div><div><label className={labelClass}>Warranty & support details</label><textarea className={inputClass} rows={4} value={form.warrantyDetails} onChange={e => set("warrantyDetails", e.target.value)} /></div><div><label className={labelClass}>What&apos;s covered? (one point per line)</label><textarea className={inputClass} rows={5} value={form.covered.join("\n")} onChange={e => setForm(current => ({ ...current, covered: e.target.value.split("\n") }))} placeholder="Motherboard and internal components" /></div></section>
    <section className="clay-card p-6 space-y-5"><h2 className="text-xl font-black text-[#2d1a26]">Delivery</h2><p className="text-xs text-[#4a1a2e]/50">Leave the product fee blank to use the site setting: ₹{siteShippingFee.toLocaleString()}.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label className={labelClass}>Product delivery fee (₹)</label><input className={inputClass} type="number" min="0" value={form.deliveryFee} onChange={e => set("deliveryFee", e.target.value)} placeholder={`Site default ₹${siteShippingFee}`} /></div><div><label className={labelClass}>Delivery time</label><input className={inputClass} value={form.deliveryDays} onChange={e => set("deliveryDays", e.target.value)} /></div></div></section>
    <section className="clay-card p-6 space-y-5"><div><h2 className="text-xl font-black text-[#2d1a26]">Reviews</h2><p className="text-xs text-[#4a1a2e]/50">Customer reviews are grouped by rating. Top reviews appear first on the storefront.</p></div>{[5, 4, 3, 2, 1].map(rating => <div key={rating} className="space-y-2"><h3 className="font-black text-[#2d1a26]">{rating} star{rating !== 1 ? "s" : ""} ({reviewList.filter(review => review.rating === rating).length})</h3>{reviewList.filter(review => review.rating === rating).map(review => <div key={review.id} className="rounded-2xl border border-pink-100 p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-bold">{review.title || "Customer review"}</p><p className="text-xs text-[#4a1a2e]/50">{review.user?.name || "Customer"} · {review.user?.email || ""}</p></div><button type="button" onClick={() => toggleTop(review)} className={`text-xs font-bold ${review.isTopReview ? "text-[#e1467c]" : "text-gray-400"}`}><Star className="w-4 h-4 inline" /> {review.isTopReview ? "Top review" : "Mark top"}</button></div><p className="mt-2 text-sm text-[#4a1a2e]/70">{review.content}</p></div>)}</div>)}{reviewList.length === 0 && <p className="text-sm text-[#4a1a2e]/50">No customer reviews yet.</p>}<textarea className={inputClass} rows={4} value={form.reviews} onChange={e => set("reviews", e.target.value)} placeholder="Optional review summary" /></section>
  </form>;
}
