"use client";
import { useState } from "react";
import { Save } from "lucide-react";
import { useRouter } from "next/navigation";
import type { ContactInfo } from "@/lib/siteContent";
export default function ContactClient({ initial }: { initial: ContactInfo }) {
  const [form, setForm] = useState(initial); const [saving, setSaving] = useState(""); const router = useRouter();
  const set = (key: keyof ContactInfo, value: string | boolean) => setForm({ ...form, [key]: value });
  const save = async (section: string) => { setSaving(section); await fetch("/api/admin/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key: "CONTACT_INFO", value: form }) }); setSaving(""); router.refresh(); };
  const redirect = (which: 1 | 2, checked: boolean) => { const key = which === 1 ? "whatsapp1" : "whatsapp2"; setForm({ ...form, useWhatsapp1AsRedirect: which === 1 && checked, useWhatsapp2AsRedirect: which === 2 && checked, whatsappRedirect: checked ? form[key] : "" }); };
  return <div className="space-y-8 pb-12"><header><h1 className="text-3xl font-black text-[#2d1a26]">Contact</h1><p className="text-sm text-[#4a1a2e]/50 mt-1">Manage store details, contact channels and social links.</p></header>
    <Section title="Store details" saving={saving === "store"} onSave={() => save("store")}><Field label="Address" value={form.address} onChange={v => set("address", v)} area /><Field label="Google Maps directions URL" value={form.googleMapsAddress} onChange={v => set("googleMapsAddress", v)} /><div className="grid md:grid-cols-2 gap-5"><Field label="Monday - Saturday" value={form.mondaySaturdayHours} onChange={v => set("mondaySaturdayHours", v)} /><Field label="Sunday" value={form.sundayHours} onChange={v => set("sundayHours", v)} /></div></Section>
    <Section title="Contacts" saving={saving === "contacts"} onSave={() => save("contacts")}><Field label="Support contact" value={form.supportContact} onChange={v => set("supportContact", v)} /><div className="grid md:grid-cols-2 gap-5"><div><Field label="WhatsApp contact 1" value={form.whatsapp1} onChange={v => set("whatsapp1", v)} /><Check checked={form.useWhatsapp1AsRedirect} onChange={v => redirect(1, v)} text="Use as WhatsApp redirect" /></div><div><Field label="WhatsApp contact 2" value={form.whatsapp2} onChange={v => set("whatsapp2", v)} /><Check checked={form.useWhatsapp2AsRedirect} onChange={v => redirect(2, v)} text="Use as WhatsApp redirect" /></div></div><Field label="WhatsApp redirect" value={form.whatsappRedirect} onChange={v => set("whatsappRedirect", v)} disabled={form.useWhatsapp1AsRedirect || form.useWhatsapp2AsRedirect} /></Section>
    <Section title="Social links" saving={saving === "social"} onSave={() => save("social")}><div className="grid md:grid-cols-3 gap-5"><Field label="Instagram link" value={form.instagram} onChange={v => set("instagram", v)} /><Field label="Facebook link" value={form.facebook} onChange={v => set("facebook", v)} /><Field label="YouTube link" value={form.youtube} onChange={v => set("youtube", v)} /></div></Section>
  </div>;
}
function Section({ title, saving, onSave, children }: { title: string; saving: boolean; onSave: () => void; children: React.ReactNode }) { return <section className="clay-card p-7 space-y-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={onSave} disabled={saving} className="clay-btn flex gap-2 items-center px-4 py-2 text-white font-bold text-sm"><Save className="w-4 h-4" />{saving ? "Saving..." : "Save section"}</button></div>{children}</section>; }
function Field({ label, value, onChange, area, disabled }: { label: string; value: string; onChange: (v: string) => void; area?: boolean; disabled?: boolean }) { return <label className="block text-[10px] font-black text-[#e1467c] uppercase tracking-widest">{label}{area ? <textarea disabled={disabled} value={value} onChange={e => onChange(e.target.value)} className="mt-2 w-full min-h-28 rounded-2xl p-4 border border-pink-200 bg-white/70 text-sm normal-case disabled:opacity-60" /> : <input disabled={disabled} value={value} onChange={e => onChange(e.target.value)} className="mt-2 w-full rounded-2xl p-3 border border-pink-200 bg-white/70 text-sm normal-case disabled:opacity-60" />}</label>; }
function Check({ checked, onChange, text }: { checked: boolean; onChange: (v: boolean) => void; text: string }) { return <label className="mt-3 flex items-center gap-2 text-sm font-semibold text-[#4a1a2e] cursor-pointer"><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} className="accent-pink-500" />{text}</label>; }
