"use client";
import { useState } from "react";
import { Save, Upload, Image as ImageIcon, Shield, Leaf, Target, Award } from "lucide-react";
import { useRouter } from "next/navigation";
import type { AboutPageContent } from "@/lib/siteContent";

const icons = [Shield, Leaf, Target, Award];
export default function OurStoryClient({ initial }: { initial: AboutPageContent }) {
  const [form, setForm] = useState(initial); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const router = useRouter();
  const update = (key: keyof AboutPageContent, value: unknown) => setForm({ ...form, [key]: value } as AboutPageContent);
  const upload = async (index: number, file: File) => { const body = new FormData(); body.append("file", file); const res = await fetch("/api/upload", { method: "POST", body }); const data = await res.json(); if (data.url) { const images = [...form.images]; images[index] = { ...images[index], src: data.url }; update("images", images); } };
  const save = async () => { setSaving(true); const res = await fetch("/api/admin/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key: "ABOUT_PAGE", value: form }) }); setSaving(false); if (res.ok) { setSaved(true); router.refresh(); setTimeout(() => setSaved(false), 2500); } };
  return <div className="space-y-8 pb-12"><header className="flex items-start justify-between"><div><h1 className="text-3xl font-black text-[#2d1a26]">Our Story</h1><p className="text-sm text-[#4a1a2e]/50 mt-1">Edit the content shown on the storefront Our Story page.</p></div><button onClick={save} disabled={saving} className="clay-btn flex gap-2 items-center px-5 py-3 text-white font-bold"><Save className="w-4 h-4" />{saved ? "Saved ✓" : saving ? "Saving..." : "Save Our Story"}</button></header>
    <section className="clay-card p-7 space-y-5"><h2 className="text-xl font-black">Hero & story</h2><Field label="Hero main text" value={form.heroTitle} maxLength={70} onChange={v => update("heroTitle", v)} /><Field label="Hero sub text" value={form.heroSubtitle} maxLength={240} onChange={v => update("heroSubtitle", v)} area /><Field label="Our Story heading" value={form.storyTitle} maxLength={60} onChange={v => update("storyTitle", v)} /><label className="block text-[10px] font-black text-[#e1467c] uppercase tracking-widest">Our Story text (one paragraph per line)<textarea value={form.storyBody.join("\n")} maxLength={1800} onChange={e => update("storyBody", e.target.value.split("\n"))} className="mt-2 w-full min-h-40 rounded-2xl p-4 border border-pink-200 bg-white/70" /></label></section>
    <section className="clay-card p-7 space-y-6"><h2 className="text-xl font-black">Story gallery (5 images)</h2><div className="grid md:grid-cols-2 gap-5">{form.images.slice(0, 5).map((image, i) => <div key={i} className="rounded-2xl border border-pink-200 p-4 space-y-3"><p className="text-[10px] font-black text-[#e1467c] uppercase">Image {i + 1}</p><input value={image.src} onChange={e => { const images = [...form.images]; images[i] = { ...images[i], src: e.target.value }; update("images", images); }} className="w-full rounded-xl p-3 border border-pink-200" placeholder="Image URL" /><label className="flex items-center justify-center gap-2 rounded-xl border-2 border-dashed border-pink-300 p-3 text-sm font-bold text-[#e1467c] cursor-pointer"><Upload className="w-4 h-4" />Upload image<input type="file" accept="image/*" className="hidden" onChange={e => e.target.files?.[0] && upload(i, e.target.files[0])} /></label>{image.src ? <img src={image.src} alt={image.alt} className="h-32 w-full object-cover rounded-xl" onError={e => { e.currentTarget.style.display = "none"; }} /> : <ImageIcon className="mx-auto text-pink-300" />}</div>)}</div></section>
    <section className="clay-card p-7 space-y-6"><div><h2 className="text-xl font-black">Core values</h2><p className="text-sm text-[#4a1a2e]/50">Titles are limited to 42 characters and descriptions to 180 characters. Icons match each card position automatically.</p></div>{form.coreValues.slice(0, 4).map((value, i) => { const Icon = icons[i]; return <div className="grid md:grid-cols-[auto_1fr_1fr] gap-4 items-start" key={i}><div className="w-12 h-12 rounded-xl bg-pink-50 flex items-center justify-center"><Icon className="text-[#e1467c]" /></div><Field label={`Value ${i + 1} heading`} value={value.title} maxLength={42} onChange={v => { const values = [...form.coreValues]; values[i] = { ...values[i], title: v }; update("coreValues", values); }} /><Field label="Description" value={value.description} maxLength={180} onChange={v => { const values = [...form.coreValues]; values[i] = { ...values[i], description: v }; update("coreValues", values); }} area /></div>; })}</section></div>;
}
function Field({ label, value, onChange, maxLength, area }: { label: string; value: string; onChange: (v: string) => void; maxLength?: number; area?: boolean }) { return <label className="block text-[10px] font-black text-[#e1467c] uppercase tracking-widest">{label}{area ? <textarea value={value} maxLength={maxLength} onChange={e => onChange(e.target.value)} className="mt-2 w-full min-h-24 rounded-2xl p-4 border border-pink-200 bg-white/70 text-sm normal-case" /> : <input value={value} maxLength={maxLength} onChange={e => onChange(e.target.value)} className="mt-2 w-full rounded-2xl p-3 border border-pink-200 bg-white/70 text-sm normal-case" />}</label>; }
