export type Product = {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice: number | null;
  stock: number;
  category: string;
  condition: string;
  imageUrl: string | null;
  imageUrls?: string | null;
  specifications?: string | null;
  technicalSpecifications?: string | null;
  nonTechnicalSpecifications?: string | null;
  showTechnicalSpecifications?: boolean;
  showNonTechnicalSpecifications?: boolean;
  discountBadge: string | null;
  isFeatured: boolean;
  createdAt: Date;
  updatedAt: Date;
};
