'use client';
import { useState } from 'react';
import { Specification } from '@/lib/parseSpecs';
import { ShieldCheck, ArrowRightLeft, Star } from 'lucide-react';

type Review = { id: string; rating: number; title: string | null; content: string; isTopReview: boolean; createdAt: string; user: { name: string } | null };
interface Props { description: string; specifications: Specification[]; condition: string; technicalSpecifications?: Specification[]; nonTechnicalSpecifications?: string | null; showTechnicalSpecifications?: boolean; showNonTechnicalSpecifications?: boolean; warrantyMonths?: number | null; warrantyDetails?: string | null; coveredItems?: string[]; supportDetails?: string | null; reviews?: string | null; qualityTitle?: string | null; qualityText?: string | null; replacementTitle?: string | null; replacementText?: string | null; customerReviews?: Review[]; }

export function ProductTabs({ description, specifications, condition, technicalSpecifications, nonTechnicalSpecifications, showTechnicalSpecifications = true, showNonTechnicalSpecifications = true, warrantyMonths, warrantyDetails, coveredItems, supportDetails, reviews, qualityTitle, qualityText, replacementTitle, replacementText, customerReviews = [] }: Props) {
  const [activeTab, setActiveTab] = useState<'overview' | 'specs' | 'warranty' | 'reviews'>('overview'); const [ratingFilter, setRatingFilter] = useState('all');
  const technical = technicalSpecifications?.length ? technicalSpecifications : specifications; const points = coveredItems?.length ? coveredItems : ['Motherboard and internal components', 'Display screen (excluding physical damage or liquid spills)', 'RAM and Storage drives', 'Keyboard and Trackpad functionality'];
  const visibleReviews = customerReviews.filter(review => ratingFilter === 'all' || review.rating === Number(ratingFilter)); const average = customerReviews.length ? (customerReviews.reduce((sum, review) => sum + review.rating, 0) / customerReviews.length).toFixed(1) : null;
  const tabs = [{ id: 'overview', label: 'Overview' }, { id: 'specs', label: 'Specifications' }, { id: 'warranty', label: 'Warranty & Support' }, { id: 'reviews', label: 'Reviews' }];
  return <div className="mt-12 bg-white rounded-3xl shadow-sm border border-gray-100 overflow-hidden"><div className="flex overflow-x-auto border-b border-gray-100 scrollbar-hide">{tabs.map(tab => <button key={tab.id} onClick={() => setActiveTab(tab.id as any)} className={`whitespace-nowrap py-4 px-6 md:px-8 text-sm md:text-base font-bold transition-colors relative ${activeTab === tab.id ? 'text-primary' : 'text-gray-500 hover:text-gray-900 bg-gray-50/50 hover:bg-white'}`}>{tab.label}{activeTab === tab.id && <div className="absolute bottom-0 left-0 w-full h-1 bg-primary rounded-t-full" />}</button>)}</div><div className="p-6 md:p-8 min-h-[300px]">
    {activeTab === 'overview' && <div className="prose prose-sm md:prose-base max-w-none text-gray-600"><h3 className="text-xl font-bold text-gray-900 mb-4">Product Overview</h3><p className="whitespace-pre-wrap leading-relaxed">{description}</p><div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6"><div className="bg-primary/5 p-4 rounded-2xl border border-primary/10"><ShieldCheck className="h-8 w-8 text-primary mb-3" /><h4 className="font-bold text-gray-900 mb-1">{qualityTitle || 'Quality Checked'}</h4><p className="text-sm text-gray-600">{qualityText || 'Thoroughly tested by our expert technicians for optimal performance.'}</p></div><div className="bg-primary/5 p-4 rounded-2xl border border-primary/10"><ArrowRightLeft className="h-8 w-8 text-primary mb-3" /><h4 className="font-bold text-gray-900 mb-1">{replacementTitle || '7 Days Replacement'}</h4><p className="text-sm text-gray-600">{replacementText || 'Easy replacement if any defect is found within 7 days of delivery.'}</p></div></div></div>}
    {activeTab === 'specs' && <div className="space-y-8">{showTechnicalSpecifications && <div><h3 className="text-xl font-bold text-gray-900 mb-6">Technical Specifications</h3><div className="rounded-2xl border border-gray-200 overflow-hidden"><table className="w-full text-left text-sm text-gray-600"><tbody>{technical.map((spec, i) => <tr key={i} className={i % 2 === 0 ? 'bg-gray-50' : 'bg-white'}><th className="px-6 py-4 font-semibold text-gray-900 border-r border-gray-200 w-1/3">{spec.key}</th><td className="px-6 py-4">{spec.value}</td></tr>)}</tbody></table></div></div>}{showNonTechnicalSpecifications && nonTechnicalSpecifications && <div><h3 className="text-xl font-bold text-gray-900 mb-4">Non-technical Specifications</h3><p className="whitespace-pre-wrap text-gray-600 leading-relaxed">{nonTechnicalSpecifications}</p></div>}</div>}
    {activeTab === 'warranty' && <div className="space-y-6"><h3 className="text-xl font-bold text-gray-900">Warranty & Support Details</h3><div className="bg-blue-50 border border-blue-100 rounded-2xl p-6"><h4 className="font-bold text-blue-900 text-lg mb-2">Standard Warranty</h4><p className="text-blue-800 text-sm md:text-base leading-relaxed whitespace-pre-wrap">This {condition === 'Used' ? 'In-built' : condition} product comes with a <strong>{warrantyMonths ? `${warrantyMonths} Months` : condition === 'New' ? '1 Year' : '6 Months'}</strong> standard warranty. {warrantyDetails || 'Our warranty covers any hardware defects that may occur during normal usage.'}</p></div><div><h4 className="font-bold text-gray-900 mb-3">What's Covered?</h4><ul className="list-disc pl-5 space-y-2 text-gray-600 text-sm md:text-base">{points.map((point, i) => <li key={i}>{point}</li>)}</ul></div><div><h4 className="font-bold text-gray-900 mb-3">Support Channels</h4><p className="text-gray-600 text-sm md:text-base whitespace-pre-wrap">{supportDetails || 'For warranty claims or technical support, please contact us at support@lapitex.com or call us at +91 6200144824.'}</p></div></div>}
    {activeTab === 'reviews' && <div><div className="flex flex-wrap items-center justify-between gap-4 mb-8"><h3 className="text-xl font-bold text-gray-900">Customer Reviews</h3><div className="flex items-center gap-3"><div className="flex text-yellow-400">{[1,2,3,4,5].map(i => <Star key={i} className={`w-5 h-5 ${average && i <= Math.round(Number(average)) ? 'fill-current' : 'text-yellow-200'}`} />)}</div><span className="font-bold text-gray-900">{average ? `${average}/5` : 'No ratings'}</span><select value={ratingFilter} onChange={e => setRatingFilter(e.target.value)} className="rounded-xl border border-gray-200 px-3 py-2 text-sm"><option value="all">All ratings</option>{[5,4,3,2,1].map(r => <option key={r} value={r}>{r} stars</option>)}</select></div></div>{reviews && <div className="rounded-2xl bg-pink-50 p-5 text-gray-600 whitespace-pre-wrap mb-6">{reviews}</div>}<div className="space-y-6">{visibleReviews.map(review => <div key={review.id} className="border-b border-gray-100 pb-6"><div className="flex items-center justify-between mb-2"><div><p className="font-bold text-gray-900">{review.title || 'Customer review'}</p><p className="text-xs text-gray-500">{review.user?.name || 'Customer'} {review.isTopReview && '· Top review'}</p></div><div className="flex text-yellow-400">{[1,2,3,4,5].map(i => <Star key={i} className={`w-4 h-4 ${i <= review.rating ? 'fill-current' : 'text-yellow-200'}`} />)}</div></div><p className="text-gray-600 text-sm mt-3 leading-relaxed">{review.content}</p></div>)}{customerReviews.length === 0 && <p className="text-gray-500">No customer reviews yet.</p>}{customerReviews.length > 0 && visibleReviews.length === 0 && <p className="text-gray-500">No reviews match this rating.</p>}</div></div>}
  </div></div>;
}
